version: 2
updates:
  - package-ecosystem: 'bundler'
    directory: '/'
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "08:00"
      timezone: "Asia/Tokyo"
  - package-ecosystem: "npm"
    directory: '/'
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "08:00"
      timezone: "Asia/Tokyo"
