plugins:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  TargetRubyVersion: 3.2
  NewCops: disable
  SuggestExtensions: false

  Exclude:
    - '**/templates/**/*'
    - '**/vendor/**/*'
    - 'app/views/**/*'
    - 'config/**/*'
    - 'config.ru'
    - 'node_modules/**/*'
    - 'db/migrate/*'
    - 'db/seeds.rb'
    - 'db/schema.rb'
    - 'storage/**/*'
    - 'tmp/**/*'
    - 'bin/**/*'
    - 'Rakefile'

Performance:
  Exclude:
    - '**/test/**/*'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*.rb'
    - 'lib/tasks/*.rake'
  Max: 16

Metrics/BlockLength:
  Exclude:
    - 'lib/tasks/*.rake'

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/AbcSize:
  Max: 50

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 8

RSpec/ContextWording:
  Enabled: false
